channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - cython
    - pip:
        - git+https://github.com/mirnylab/cooltools
        - git+https://github.com/nvictus/pybbi.git
        - git+https://github.com/nvictus/lavaburst.git
        - bioframe
        - cooler
        - multiprocess
