channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - numpy
    - scipy
    - cython
    - matplotlib
    - seaborn
    - bokeh
    - pandas
    - h5py
    - numba
    - dask
    - cytoolz
    - ipywidgets
    - parallel
    - pbgzip
    - samtools>=1.4
    - sra-tools>=2.8.1
    - ucsc-fetchchromsizes
    - bedtools
    - biopython
    - pyfaidx
    - pysam
    - pip:
        - git+https://github.com/mirnylab/pairsamtools
        - git+https://github.com/mirnylab/cooltools
        - git+https://github.com/nvictus/pybbi.git
        - git+https://github.com/nvictus/lavaburst.git
        - bioframe
        - cooler
        - multiprocess
